<?php

namespace AppcourseBundle\Repository;

/**
 * listeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class listeRepository extends \Doctrine\ORM\EntityRepository
{
}
