<?php

namespace AppcourseBundle\Repository;


/**
 * ListeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ListeRepository extends \Doctrine\ORM\EntityRepository
{

public function findListe($id)
{
  $qb = $this->createQueryBuilder('l
  	');

  $qb
    ->where('l.id = :id')
    ->setParameter('id', $id)
    ->leftJoin('l.produits', 'p')
    ->addSelect('p')
    ->leftJoin('p.rayon', 'r')
    ->addSelect('r')
    ->addOrderBy('r.nom', 'ASC')
    ->addOrderBy('p.nom', 'ASC')
	;

  return $qb
    ->getQuery()
    ->getSingleResult()
  ;
}


}
