<?php

namespace AppcourseBundle\Repository;

use Doctrine\ORM\QueryBuilder;

/**
 * ProduitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProduitRepository extends \Doctrine\ORM\EntityRepository
{
	public function produitAvecRayon()
	{
		$qb = $this
			->createQueryBuilder('p')
			->leftJoin('p.rayon', 'ray')
			->addSelect('ray')
			->orderBy('p.nom', 'ASC')
		;

		return $qb->getQuery()->getResult();
	}

}
