<?php

namespace AppcourseBundle\Repository;

/**
 * rayonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class rayonRepository extends \Doctrine\ORM\EntityRepository
{
}
