appcourse_homepage:
    path:     /
    defaults: { _controller: AppcourseBundle:Default:index }

appcourse_view_liste:
    path:    /{id}
    defaults: { _controller: AppcourseBundle:Default:view }
    requirements:
        id: \d+

appcourse_add_liste:
    path:    /add
    defaults: { _controller: AppcourseBundle:Default:add }

appcourse_edit_liste:
    path:    /edit/{id}
    defaults: { _controller: AppcourseBundle:Default:edit }
    requirements:
        id: \d+

appcourse_delete_liste:
    path:    /delete/{id}
    defaults: { _controller: AppcourseBundle:Default:delete }
    requirements:
        id: \d+

appcourse_index_rayon:
    path:    /rayon
    defaults: { _controller: AppcourseBundle:Rayon:rayonIndex }

appcourse_add_rayon:
    path:    /rayon/add 
    defaults: { _controller: AppcourseBundle:Rayon:rayonAdd }

appcourse_edit_rayon:
    path:    /rayon/edit/{id}
    defaults: { _controller: AppcourseBundle:Rayon:rayonEdit }
    requirements:
        id: \d+

appcourse_delete_rayon:
    path:    /rayon/delete/{id}
    defaults: { _controller: AppcourseBundle:Rayon:rayonDelete }
    requirements:
        id: \d+

appcourse_index_produit:
    path:    /produit 
    defaults: { _controller: AppcourseBundle:Default:produitIndex }

appcourse_add_produit:
    path:    /produit/add 
    defaults: { _controller: AppcourseBundle:Default:produitAdd }

appcourse_edit_produit:
    path:    /produit/edit/{id}
    defaults: { _controller: AppcourseBundle:Default:produitEdit }
    requirements:
        id: \d+

appcourse_delete_produit:
    path:    /produit/delete/{id}
    defaults: { _controller: AppcourseBundle:Default:produitDelete }
    requirements:
        id: \d+

