appcourse_homepage:
    path:     /
    defaults: { _controller: AppcourseBundle:Default:index }

appcourse_view_list:
    path:    /{id}
    defaults: { _controller: AppcourseBundle:Default:view }
    requirements:
        id: \d+

appcourse_index_rayon:
    path:    /rayon
    defaults: { _controller: AppcourseBundle:Default:rayonIndex }


appcourse_add_rayon:
    path:    /rayon/add 
    defaults: { _controller: AppcourseBundle:Default:rayonAdd }

appcourse_edit_rayon:
    path:    /rayon/edit/{id}
    defaults: { _controller: AppcourseBundle:Default:rayonEdit }
    requirements:
        id: \d+

appcourse_delete_rayon:
    path:    /rayon/delete/{id}
    defaults: { _controller: AppcourseBundle:Default:rayonDelete }
    requirements:
        id: \d+

appcourse_index_produit:
    path:    /produit 
    defaults: { _controller: AppcourseBundle:Default:produitIndex }

appcourse_add_produit:
    path:    /produit/add 
    defaults: { _controller: AppcourseBundle:Default:produitAdd }